version: '3'

services:

  kpts-management:
    container_name: kpts-management
    image: hazelcast/management-center
    network_mode: "host"

  kpts-worker:
    image: hazelcast/hazelcast
    volumes:
        - ./config:/config
    environment:
        - "JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml"
    network_mode: "host"
    depends_on:
        - kpts-management

