version: '3'

services:

  kpts-management:
    container_name: kpts-management
    image: hazelcast/management-center
    ports:
        - 8080:8080

  kpts-worker:
    image: hazelcast/hazelcast
    volumes:
        - ./config:/config
        - ../build/libs:/libs
    ports:
        - 5701:5701
    environment:
        - "JAVA_OPTS=-Dhazelcast.config=/config/hazelcast.xml"
        - "CLASSPATH=/libs"
    depends_on:
        - kpts-management


